### ISSUE TITLE
.gitignore everywhere makes sure I do not see my modifications for a custom installation

### ISSUE THREAD

**Issue by hfreude** [ibm-s390-cloud/ocp-kvm-ipi-automation#135]
See title. There are multiple .gitignore spread in this repo making sure I do not see my modifcations or new files with git status. For example see what happens when I add a file ansible/host_vars/m83lp51.lnxne.boe.yaml the ansible/host_vars/.gitignore makes shure I don't see this file. That's strange and confusing.

**Comment by haubenr** [comment]
The various `.gitignore` files in this repository have been created deliberately to ensure that under no circumstances user-specific custom files are checked into the code base, neither by mistake nor by intent. If you do have the need for `git diff` for your custom files (e.g. host configuraion files) I suggest you fork this repository into your own dedicated GitHub namespace and make the required changes in your fork depending on your personal needs and preferences.

**Comment by hfreude** [comment]
I do understand this idea.
However, it totally contradicts to git and any version control. However, If you think this is the right way ...
