### ISSUE TITLE
ocp 4.12 installation does not work with current 'main' branch

### ISSUE THREAD

**Issue by hfreude** [ibm-s390-cloud/ocp-kvm-ipi-automation#137]
My installation attempts fail with:

 [started TASK: ocp_prepare_install : download CoreOS installation files from Red Hat mirror on m83lp51.lnxne.boe]
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (10 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (9 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (8 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (7 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (6 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (5 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (4 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (3 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (2 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (1 retries left).

TASK [ocp_prepare_install : download CoreOS installation files from Red Hat mirror] *******************************************************************************************
failed: [m83lp51.lnxne.boe] (item=1.0) => changed=false 
  ansible_loop_var: delay
  attempts: 10
  delay: 1.0
  msg: 'Unsupported parameters for (ansible.builtin.get_url) module: decompress. Supported parameters include: seuser, checksum, owner, url_username (username), mode, unsafe_writes, serole, validate_certs, headers, use_gssapi, url_password (password), timeout, tmp_dest, attributes (attr), dest, unredirected_headers, selevel, sha256sum, url, client_key, use_proxy, force (thirsty), setype, client_cert, backup, http_agent, group, force_basic_auth.'
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (10 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (9 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (8 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (7 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (6 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (5 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (4 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (3 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (2 retries left).
FAILED - RETRYING: [m83lp51.lnxne.boe]: download CoreOS installation files from Red Hat mirror (1 retries left).
failed: [m83lp51.lnxne.boe] (item=4.0) => changed=false 
  ansible_loop_var: delay
  attempts: 10
  delay: 4.0
  msg: 'Unsupported parameters for (ansible.builtin.get_url) module: decompress. Supported parameters include: tmp_dest, checksum, backup, url_password (password), owner, sha256sum, timeout, unsafe_writes, use_proxy, unredirected_headers, client_key, setype, group, url, selevel, dest, validate_certs, mode, force (thirsty), attributes (attr), http_agent, url_username (username), use_gssapi, client_cert, headers, serole, force_basic_auth, seuser.'

**Comment by haubenr** [comment]
Ansible keeps evolving and so do these playbooks. As mentioned in the current documentation (see: https://github.com/ibm-s390-cloud/ocp-kvm-ipi-automation/blob/567ce1116ed3a9f2c9f69449940bb26a8460b143/docs/DOCUMENTATION.md?plain=1#L12) please update your local Ansible installation to at least version 4.12.

**Comment by hfreude** [comment]
Ok, well I used tuxmaker ...
